fix: update package name
eslint-community/eslint-plugin-mysticatea pull request #6
Opened 2022-10-12 01:36 UTC by MichaelDeBoey

2022-10-12 01:37 UTC, MichaelDeBoey commented
I seems like ESLint can't find the plugin because we're not adhering [naming conventions](https://eslint.org/docs/latest/user-guide/configuring/plugins#naming-convention) anymore with renaming the package to `@eslint-community/mysticatea__eslint-plugin`.

@eslint-community/eslint-tsc @eslint-community/mysticatea-eslint-plugin Should we rename the package (& repo) to `@eslint-community/eslint-plugin-mysticatea` instead? 🤔

2022-10-12 01:37 UTC, MichaelDeBoey commented
I seems like ESLint can't find the plugin because we're not adhering [naming conventions](https://eslint.org/docs/latest/user-guide/configuring/plugins#naming-convention) anymore with renaming the package to `@eslint-community/mysticatea__eslint-plugin`.

@eslint-community/eslint-tsc @eslint-community/core-team @eslint-community/mysticatea-eslint-plugin Should we rename the package (& repo) to `@eslint-community/eslint-plugin-mysticatea` instead? 🤔

2022-10-13 17:06 UTC, nzakas commented
> Should we rename the package (& repo) to @eslint-community/eslint-plugin-mysticatea instead? 🤔

Yes. For plugins, names must begin with `eslint-plugin-`.

2022-10-13 23:26 UTC, ota-meshi requested changes

2022-10-13 23:26 UTC, ota-meshi commented on README.md
> +[![Dependency Status](https://david-dm.org/eslint-community/mysticatea__eslint-plugin.svg)](https://david-dm.org/eslint-community/mysticatea__eslint-plugin)
```suggestion
[![Build Status](https://github.com/eslint-community/eslint-plugin-mysticatea/workflows/CI/badge.svg)](https://github.com/eslint-community/eslint-plugin-mysticatea/actions)
[![codecov](https://codecov.io/gh/eslint-community/eslint-plugin-mysticatea/branch/master/graph/badge.svg)](https://codecov.io/gh/eslint-community/eslint-plugin-mysticatea)
[![Dependency Status](https://david-dm.org/eslint-community/eslint-plugin-mysticatea.svg)](https://david-dm.org/eslint-community/eslint-plugin-mysticatea)
```

2022-10-13 23:26 UTC, ota-meshi commented on README.md
> +- [GitHub Releases](https://github.com/eslint-community/mysticatea__eslint-plugin/releases)
```suggestion
- [GitHub Releases](https://github.com/eslint-community/eslint-plugin-mysticatea/releases)
```

2022-10-13 23:26 UTC, ota-meshi commented on package.json
> +    "url": "https://github.com/eslint-community/mysticatea__eslint-plugin"
```suggestion
    "url": "https://github.com/eslint-community/eslint-plugin-mysticatea"
```

2022-10-13 23:26 UTC, ota-meshi commented on package.json
> +    "url": "https://github.com/eslint-community/mysticatea__eslint-plugin/issues"
```suggestion
    "url": "https://github.com/eslint-community/eslint-plugin-mysticatea/issues"
```

2022-10-13 23:26 UTC, ota-meshi commented on package.json
> +  "homepage": "https://github.com/eslint-community/mysticatea__eslint-plugin#readme"
```suggestion
  "homepage": "https://github.com/eslint-community/eslint-plugin-mysticatea#readme"
```

2022-10-13 23:26 UTC, ota-meshi commented on lib/rules/arrow-parens.js
> +                "https://github.com/eslint-community/mysticatea__eslint-plugin/blob/v13.0.0/docs/rules/arrow-parens.md",
```suggestion
                "https://github.com/eslint-community/eslint-plugin-mysticatea/blob/v13.0.0/docs/rules/arrow-parens.md",
```

2022-10-13 23:26 UTC, ota-meshi commented on lib/rules/block-scoped-var.js
> +                "https://github.com/eslint-community/mysticatea__eslint-plugin/blob/v13.0.0/docs/rules/block-scoped-var.md",
```suggestion
                "https://github.com/eslint-community/eslint-plugin-mysticatea/blob/v13.0.0/docs/rules/block-scoped-var.md",
```

2022-10-13 23:26 UTC, ota-meshi commented on lib/rules/no-instanceof-array.js
> +                "https://github.com/eslint-community/mysticatea__eslint-plugin/blob/v13.0.0/docs/rules/no-instanceof-array.md",
```suggestion
                "https://github.com/eslint-community/eslint-plugin-mysticatea/blob/v13.0.0/docs/rules/no-instanceof-array.md",
```

2022-10-13 23:26 UTC, ota-meshi commented on lib/rules/no-instanceof-wrapper.js
> +                "https://github.com/eslint-community/mysticatea__eslint-plugin/blob/v13.0.0/docs/rules/no-instanceof-wrapper.md",
```suggestion
                "https://github.com/eslint-community/eslint-plugin-mysticatea/blob/v13.0.0/docs/rules/no-instanceof-wrapper.md",
```

2022-10-13 23:26 UTC, ota-meshi commented on lib/rules/no-literal-call.js
> +                "https://github.com/eslint-community/mysticatea__eslint-plugin/blob/v13.0.0/docs/rules/no-literal-call.md",
```suggestion
                "https://github.com/eslint-community/eslint-plugin-mysticatea/blob/v13.0.0/docs/rules/no-literal-call.md",
```

2022-10-13 23:26 UTC, ota-meshi commented on lib/rules/no-this-in-static.js
> +                "https://github.com/eslint-community/mysticatea__eslint-plugin/blob/v13.0.0/docs/rules/no-this-in-static.md",
```suggestion
                "https://github.com/eslint-community/eslint-plugin-mysticatea/blob/v13.0.0/docs/rules/no-this-in-static.md",
```

2022-10-13 23:26 UTC, ota-meshi commented on lib/rules/no-use-ignored-vars.js
> +                "https://github.com/eslint-community/mysticatea__eslint-plugin/blob/v13.0.0/docs/rules/no-use-ignored-vars.md",
```suggestion
                "https://github.com/eslint-community/eslint-plugin-mysticatea/blob/v13.0.0/docs/rules/no-use-ignored-vars.md",
```

2022-10-13 23:26 UTC, ota-meshi commented on lib/rules/no-useless-rest-spread.js
> +                "https://github.com/eslint-community/mysticatea__eslint-plugin/blob/v13.0.0/docs/rules/no-useless-rest-spread.md",
```suggestion
                "https://github.com/eslint-community/eslint-plugin-mysticatea/blob/v13.0.0/docs/rules/no-useless-rest-spread.md",
```

2022-10-13 23:26 UTC, ota-meshi commented on lib/rules/prefer-for-of.js
> +                "https://github.com/eslint-community/mysticatea__eslint-plugin/blob/v13.0.0/docs/rules/prefer-for-of.md",
```suggestion
                "https://github.com/eslint-community/eslint-plugin-mysticatea/blob/v13.0.0/docs/rules/prefer-for-of.md",
```

2022-10-13 23:35 UTC, ota-meshi approved these changes
Looks good to me! Thank you!

2022-10-13 23:39 UTC, merged